version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rate-limiting-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - gateway-network

  gateway:
    build: .
    container_name: rate-limiting-gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_POOL_SIZE=10
      - RATE_LIMIT_PER_MINUTE=60
      - RATE_LIMIT_PER_HOUR=1000
      - RATE_LIMIT_PER_DAY=10000
      - RATE_LIMIT_MONTHLY_QUOTA=100000
      - TARGET_URL=http://httpbin.org
      - TARGET_TIMEOUT=30s
      - LOG_LEVEL=info
      - LOG_JSON=true
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - gateway-network
    restart: unless-stopped

  # Optional: Add a test upstream service for development
  test-upstream:
    image: kennethreitz/httpbin
    container_name: test-upstream
    ports:
      - "8000:80"
    networks:
      - gateway-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  gateway-network:
    driver: bridge 